# .streamlit/secrets.toml
RAPIDAPI_KEY = "3547487c12msh9f207af97364374p1451e8jsnd77e2bbc56f8"
# .streamlit/secrets.toml
[email_credentials]
sender_email = "leandrovitor0@gmail.com"
sender_password = "fner rimi lfdf zapo"
